### ISSUE TITLE
Set ApexDoc as commenting standard

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/salesforce-docs#7]
Current CFPB Salesforce standards set the comment blocks like:

```
/*------------------------------------------------------------
Author:       Joe Somebody
Company:       Salesforce.com
Description:   A utility class for the contact trigger
Inputs:        "customers" - Contact objects that are being triggered
               "oldCustomers" - Contacts object values before trigger event
               "ta" - Trigger action that is occurring
Test Class:    CustomerManagementTest
History
<Date>      <Authors Name>     <Brief Description of Change>
------------------------------------------------------------*/
```

Instead, it seems preferable to follow https://github.com/SalesforceFoundation/ApexDoc, which follows familiar javadoc and jsdoc syntax (in use in other CFPB projects) and provides a tool to aggregate documentation.

**Comment by virtix** [comment]
I think @author and @date can be made optional as those are included as part of the git commit

The specific section and file that needs updating is: https://github.com/cfpb/salesforce-docs/blob/master/_pages/Source-code-and-configuration-management.md#commenting

**Comment by anselmbradford** [comment]
Closing as this is in the docs now. 

> I think @author and @date can be made optional as those are included as part of the git commit

Yeah, if author is making the commit. It's less clear if Jenkins is making the commit.
